service: notifications

provider:
  name: google
  stage: prod
  region: us-central1
  project: tribal-artifact-263821
  credentials: /Users/jorge.haddad/.gcloud/tribal-artifact-263821-61b1fe367269.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - venv/**
    - package.json
    - package-lock.json
    - .serverless/**
    - .idea/**
    - notifications_vars.json

functions:
  sms_notifications:
    memorySize: 128
    timeout: 120s
    runtime: python37
    handler: notify_sms
    serviceAccount: notify-function-agent@tribal-artifact-263821.iam.gserviceaccount.com
    labels:
      service: notifications
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/tribal-artifact-263821/topics/send_notification
    environment:
      LOG_LEVEL: DEBUG
      VARS_BUCKET: web-parser-vars
      VARS_BLOB: notifications_vars.json
      FROM_SMS_NUMBER: '+18059792121'
  email_notifications:
    memorySize: 128
    timeout: 120s
    runtime: python37
    handler: notify_email
    serviceAccount: notify-function-agent@tribal-artifact-263821.iam.gserviceaccount.com
    labels:
      service: notifications
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/tribal-artifact-263821/topics/send_notification
    environment:
      LOG_LEVEL: DEBUG
      VARS_BUCKET: web-parser-vars
      VARS_BLOB: notifications_vars.json
